### ISSUE TITLE
Sharing pipeline from personal workspace is still accessible in the docs

### ISSUE THREAD

**Issue by mbosio85** [seqeralabs/nf-tower-docs#219]
Hello,

Even if we removed the sharing feature and it is not present in the navigation panel, there still is an accessible page that describes the sharing of a pipeline from the personal workspace:
https://help.tower.nf/22.2/monitoring/sharing/

This page should not be there now that the feature is not available.

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/9932848/181485931-ce417800-fab9-43ed-9d21-6fc69a103bac.png">

**Comment by abhi18av** [comment]
I was also a bit perplexed since this particular page is commented out in the index https://github.com/seqeralabs/nf-tower-docs/blob/5ab553c4663e7d3437dde43a7f836b13497f2125/mkdocs.yml#L109

But after a quick chat with Mattia, it seems the search functionality still finds the "hidden" page. @gwright99 @markpanganiban , let's remove this page completely as soon as the https://github.com/seqeralabs/nf-tower-cloud/pull/3496 PR is merged.
