### ISSUE TITLE
Improve documentation for Container credentials 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#271]
The documentation for the setup of Container registry credentials should be more detailed and provide the user with a better description of the precise steps to be accomplished to configure the credentials for each specified cloud vendor. 

For example when using Google Artifact registry the following steps are needed: 

1. Creare a [Google service account](https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key) keys granting access to Google Artifact registry  
2. Open the Tower credentials manager page
3. Select "Container registry" as provider 
4. Specify `_json_key_base64` as user name 
5. Encode the key json file content in base64 and use it as password 
6. Specify the artifact repository host name in the "Registry server" field e.g `us-east1-docker.pkg.dev` 
7. Finally add `wave { enabled=true }` in the "Nextflow config" field when launching the pipeline execution 

More context https://nextflow.slack.com/archives/C02TPTREJ03/p1667316919475809?thread_ts=1667316876.802499&cid=C02TPTREJ03

**Comment by gwright99** [comment]
Piggybacking on this to suggest that - IMO - we would be well-served if the docs provided more guidance on why a user would want/need to create Tower objects such as this credential and how it is used in workflow execution.

When trying to address this customer's open [Freshdesk ticket](https://support.seqera.io/a/tickets/2442) this morning, I was looking for the exact difference between how Google (Service Account) credentials are used in a workflow vs how Google (container registry) credentials are used. 

I went to the help.tower.nf docs and did not find the answer; they clearly explained **how** to fill in the fields but not the context of **why** I was doing it and what problem would be solved by doing so. 

I think adding a bit more context would lead to a better user experience and potentially lead to more self-resolution rather than having to request support.

**Comment by pditommaso** [comment]
100% how *and* why
