### ISSUE TITLE
Improve Google Artifact Registry credentials docs 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/nf-tower-docs#303]
The Google container credentials documentation should be renamed and be focused on "Google Artifact Registry" . 

Also, it would be useful to give to provide more example and instruction how to encode the service account file to base64. 

Finally it should be included a link to the Google Docs where the user can find more detailed instruction ie. https://cloud.google.com/artifact-registry/docs/docker/authentication

**Comment by llewellyn-sl** [comment]
Removing references and links to Container Registry. 

The Google AR docs are currently linked in the page's introductory paragraph. These docs also detail the steps needed to base64-encode the service account key.

**Comment by pditommaso** [comment]
> Removing references and links to Container Registry.

Makes sense 

> 
Removing references and links to Container Registry.

The Google AR docs are currently linked in the page's introductory paragraph. These docs also detail the steps needed to base64-encode the service account key.

**Comment by gwright99** [comment]
The link to the Google docs are a good start, but they don't cover a scenario we encountered while troubleshooting a client issue last week: **discrepancies in how the `base64` command's stdout**.

Example: 

1. Running `base64 somefile.json > anotherfile` on OSX, returned a output that was not broken up with line feeds: 
![image](https://user-images.githubusercontent.com/1309341/212739765-6934bd1d-fe52-4e68-bbb8-c95b0148aaef.png)

2. Running `base64 somefile.json > anotherfile` on Ubuntu 20.04 (running on WSL2) returned output that was broken up by line feeds (which caused credential creation to fail when pasted into Tower):
![image](https://user-images.githubusercontent.com/1309341/212740186-f2e29e2b-e74a-4c8e-97b3-263deea2e8c6.png)

3. To solve the Ubuntu 20.04 on WSL2 behaviour, you have to modify the base64 command to strip line feeds: `base64 somefile.json | tr -d \\n > anotherfile`. 

I did not see this scenario covered in the GCP docs, yet the behaviour gave the appearance that Tower wasn't working (when in fact the problem was that an invalid base64 string was being pasted in by the user).

**Note:** The base64 string I've used here as an example is for a key that has been deleted.

**Comment by pditommaso** [comment]
I think this qualifies as a Tower issue. It should strip the newlines in the encoded secret
